param(
    [string]$Container = "pos-postgres",
    [string]$DbUser = "pos",
    [string]$DbName = "posdb",
    [string]$OutFile = "servidor/scripts/sql/datos-compartidos.sql"
)

$ErrorActionPreference = "Stop"

function Info([string]$Message) {
    Write-Host "[db-seed] $Message"
}

Info "Exporting database rows from container '$Container'..."

$running = docker ps --format "{{.Names}}" | Where-Object { $_ -eq $Container }
if (-not $running) {
    throw "Container '$Container' is not running. Start it with: docker compose up -d"
}

$dump = (docker exec $Container pg_dump `
    -U $DbUser `
    -d $DbName `
    --data-only `
    --column-inserts `
    --no-owner `
    --no-privileges `
    --exclude-table-data "__EFMigrationsHistory" | Out-String)

if ($LASTEXITCODE -ne 0) {
    throw "pg_dump failed."
}

$insertMatches = [regex]::Matches($dump, '(?ms)^INSERT INTO.+?;\s*$')
$statements = @()
foreach ($m in $insertMatches) {
    $stmt = $m.Value.Trim()
    $stmt = [regex]::Replace($stmt, ';\s*$', ' ON CONFLICT DO NOTHING;')
    $statements += $stmt
}

$header = @(
    "-- Shared team inserts (auto-generated from current local DB)",
    "-- Generated by: herramientas/export-shared-seed.ps1",
    "-- Safe to replay on fresh DB because statements use ON CONFLICT DO NOTHING.",
    "",
    "BEGIN;",
    ""
)

$footer = @(
    "",
    "COMMIT;",
    ""
)

$content = ($header + $statements + $footer) -join "`r`n"
Set-Content -Path $OutFile -Value $content -Encoding UTF8

Info "Wrote $OutFile with $($statements.Count) INSERT statements."
